# Generated by Django 3.2.22 on 2023-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipe_fotos/'),
        ),
    ]
