# Generated by Django 3.2.22 on 2023-10-29 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_equipe_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=200)),
                ('area_de_estudo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('palestrante', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
