# Generated by Django 3.2.22 on 2023-11-07 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_palestra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atletica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atletica_fotos/')),
                ('membros', models.ManyToManyField(related_name='atletica_membros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
